# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('PSA', models.DecimalField(decimal_places=1, max_digits=4)),
                ('prostate_vol', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lesion_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sector', models.IntegerField()),
                ('PIRADS_score', models.IntegerField()),
                ('GLEASON_score', models.IntegerField()),
            ],
        ),
    ]
